[package]
name = "debouncer"
version = "0.1.0"
description = "cache and restore files from memory"
edition = "2021"
author = "Asjid Kalam <@odinshell>"

[dependencies]
notify = "6.1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
notify-debouncer-full = "0.3.1"
